Moved exporting to the personal repository
LykkeCity/Lykke.Tools.Erc20Exporter pull request #1
Opened 2018-11-17 11:47 UTC by OttoVT

2018-11-17 11:59 UTC, some-dev approved these changes

2018-11-19 20:01 UTC, KonstantinRyazantsev approved these changes

2018-11-19 20:02 UTC, KonstantinRyazantsev requested changes
Change base branch to test

2018-11-20 10:02 UTC, KonstantinRyazantsev approved these changes

2018-11-20 12:00 UTC, merged